# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kzViwTP-AE2_F_3dZ3uTPgzVj279Asto
"""

from fastapi import FastAPI, File, UploadFile
from model import load_resnet_model, predict_image

app = FastAPI()
model = load_resnet_model()

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    contents = await file.read()
    prediction = predict_image(contents, model)
    return {"prediction": prediction}